Fix XAmzContentSHA256Mismatch on OME-Zarr upload
- We first noticed this error on 2/27. `use_ssl=False` had not caused problems prior to then
- Setting to True resolves the issue
- use py3.10 for singularity definition since there may be a bug in asyncio with 3.11
Traceback (most recent call last):
  File "/allen/aind/scratch/cameron.arshadi/miniconda3/envs/adt/lib/python3.11/asyncio/selector_events.py", line 900, in _call_connection_lost
    self._protocol.connection_lost(exc)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'connection_lost'